In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Pokemon.csv')
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [3]:
# WAP to filter pokemons with highest hitpoints of four categories water, fire, electric, grass in all generations

In [4]:
for i in range(1,7):
    Generation = df.query(f"Generation=={i}")
    print(f"------------------Generation {i}-------------------")
    Pokemon_list = ['Water', 'Fire', 'Electric', 'Grass']
    for j in Pokemon_list:
        HitPoint = Generation['HP'][df['Type 1'] == j]
        max_hp = HitPoint.max()
        print(f"Maximum hit point of Generation {i} {j}  is " + str(max_hp))

------------------Generation 1-------------------
Maximum hit point of Generation 1 Water  is 130
Maximum hit point of Generation 1 Fire  is 90
Maximum hit point of Generation 1 Electric  is 90
Maximum hit point of Generation 1 Grass  is 95
------------------Generation 2-------------------
Maximum hit point of Generation 2 Water  is 125
Maximum hit point of Generation 2 Fire  is 115
Maximum hit point of Generation 2 Electric  is 90
Maximum hit point of Generation 2 Grass  is 80
------------------Generation 3-------------------
Maximum hit point of Generation 3 Water  is 170
Maximum hit point of Generation 3 Fire  is 80
Maximum hit point of Generation 3 Electric  is 70
Maximum hit point of Generation 3 Grass  is 99
------------------Generation 4-------------------
Maximum hit point of Generation 4 Water  is 111
Maximum hit point of Generation 4 Fire  is 91
Maximum hit point of Generation 4 Electric  is 80
Maximum hit point of Generation 4 Grass  is 100
------------------Generation 5-------------------
Maximum hit point of Generation 5 Water  is 165
Maximum hit point of Generation 5 Fire  is 110
Maximum hit point of Generation 5 Electric  is 85
Maximum hit point of Generation 5 Grass  is 114
------------------Generation 6-------------------
Maximum hit point of Generation 6 Water  is 72
Maximum hit point of Generation 6 Fire  is 86
Maximum hit point of Generation 6 Electric  is 67
Maximum hit point of Generation 6 Grass  is 123

In [5]:
# for i in range(1,7):
#     Generation = df.query(f"Generation=={i}")
#     print(f"------------------Generation {i}-------------------")
#     Pokemon_list = ['Water', 'Fire', 'Electric', 'Grass']
#     for j in Pokemon_list:
#         HitPoint = Generation[['HP']][df['Type 1'].isin([j])]
#         max_hp = HitPoint.max()
#         print(f"{j}" + str(max_hp))

In [6]:
df[['Type 1','HP','Generation']][df['Type 1'].isin(['Water', 'Fire', 'Electric', 'Grass'])]

       Type 1  HP  Generation
0       Grass  45           1
1       Grass  60           1
2       Grass  80           1
3       Grass  80           1
4        Fire  39           1
..        ...  ..         ...
763     Water  71           6
764  Electric  44           6
765  Electric  62           6
772  Electric  67           6
799      Fire  80           6

[278 rows x 3 columns]

In [7]:
# Generation1 = df.query("Generation==1")
# #Grass
# Grass = df['Type 1'] == 'Grass'
# HitPoint = Generation1['HP'][Grass]
# max_hp = HitPoint.max()
# print("Maximum hit point of Grass Generatin 1 is " + str(max_hp))